version: "3"
services:
  UnblockNetease:
    container_name: UnblockNetease
    restart: always
    image: nondanee/unblockneteasemusic:latest
    environment:
      NODE_ENV: production
    expose:
      - 8080
    command: -p 8080:18080 -s -e http://music.163.com -o ${MUSIC_SOURCE}

  UnblockV2ray:
    container_name: UnblockV2ray
    restart: always
    image: v2fly/v2fly-core:latest
    ports:
      - "${V2Ray_PORT}:58080"
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
    links:
      - UnblockNetease
    depends_on:
      - UnblockNetease
