version: "3"
services:
  UnblockNetease:
    container_name: UnblockNetease
    restart: always
    image: nondanee/unblockneteasemusic:latest
    environment:
      NODE_ENV: production
    expose:
      - 8080
    command: -p 8080:18080 -s -e http://music.163.com -o ${MUSIC_SOURCE}
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"

  UnblockNeteaseIOS:
    container_name: UnblockNeteaseIOS
    restart: always
    image: nondanee/unblockneteasemusic:latest
    environment:
      NODE_ENV: production
    expose:
      - 8081
    command: -p 8081:18081 -s -e https://music.163.com -o ${MUSIC_SOURCE}
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"

  Gost:
    container_name: Gost
    restart: always
    image: ginuerzh/gost:latest
    ports:
      - "${Gost_PORT}:58080"
    links:
      - UnblockNetease
    depends_on:
      - UnblockNetease
    command: -L=ss://rc4-md5:${PASSWORD}@:58080 -F=UnblockNetease:8080 
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"    

  GostIOS:
    container_name: GostIOS
    restart: always
    image: ginuerzh/gost:latest
    ports:
      - "${Gost_IOS_PORT}:58081"
    links:
      - UnblockNeteaseIOS
    depends_on:
      - UnblockNeteaseIOS
    command: -L=ss://rc4-md5:${PASSWORD}@:58081 -F=UnblockNeteaseIOS:8081
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"    
