version: "3"

services:
  UnblockNetease:
    container_name: UnblockNetease
    restart: always
    image: nondanee/unblockneteasemusic:latest
    environment:
      NODE_ENV: production
    expose:
      - 8080
      - 8081
    volumes:
      - ./cert/server.key:/usr/src/app/server.key
      - ./cert/server.crt:/usr/src/app/server.crt
    command: -p 8080:8081 -s -e https://music.163.com

  UnblockV2ray:
    container_name: UnblockV2ray
    restart: always
    image: v2fly/v2fly-core:latest
    ports:
      - "58080:58080"
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
    depends_on:
      - UnblockNetease
